# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  labels:
    app: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: app-container
        # Usar la imagen construida con Dockerfile.secure
        image: shopping-app:secure 
        ports:
        - containerPort: 3000
        
        # Secrets Management (Simulando la inyección de la cadena de conexión)
        env:
          - name: DB_CONNECTION_STRING
            # En un entorno real, usarías valueFrom: secretKeyRef
            value: "postgresql://user:k8s-injected-secret@db-host:5432/shop" 
          - name: NODE_ENV
            value: "production"

        # Resource Limits (Previene ataques de Denegación de Servicio por recursos)
        resources:
          limits:
            cpu: "500m"  # Limite a 0.5 CPU
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
            
        # --- Security Contexts (Punto Clave de la Demo) ---
        securityContext:
          # Ejecución como usuario de bajo privilegio (UID 1001 de Dockerfile.secure)
          runAsNonRoot: true 
          runAsUser: 1001 
          # No permite que el proceso eleve privilegios a root
          allowPrivilegeEscalation: false 
          # Hace que el sistema de archivos del contenedor sea solo de lectura
          # Esto mitiga la posibilidad de que un atacante persista código malicioso.
          readOnlyRootFilesystem: true 
          # --- Fin Security Contexts ---