# docker/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: ../
      # Usar el Dockerfile seguro por defecto
      dockerfile: docker/Dockerfile.secure 
    ports:
      - "3000:3000"
    environment:
      # Inyección de variables de entorno (Secrets Management local)
      DB_CONNECTION_STRING: "postgres://shopuser:devpassword@db:5432/shopdb"
      NODE_ENV: "development"
    depends_on:
      - db
    # Para la demo, puedes cambiar esto a 'db' para apuntar a un contenedor postgres o mysql

  db:
    # Simulación de un servicio de base de datos
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: shopdb
    volumes:
      - db_data:/var/lib/postgresql/data/
    # Nota: No exponer el puerto 5432 fuera a menos que sea necesario para la demo.

volumes:
  db_data: